config/routes.rb
Outtrippin::Application.routes.draw do
  resource 'expert', only: [:create, :show]

  resources 'users', only: [:show, :destroy, :edit, :update] do
    put 'update_avatar'
  end
  resources 'user_sessions', only: [:new, :create, :destroy]
  resources 'password_resets', only: [:new, :create, :edit, :update]

  resources 'itineraries', only: [:index, :show, :create, :update] do
    member do
      get 'details'
      get 'gp'
      get 'email_form'
      get 'duration'
      get 'travelers'
      get 'budget'
      get 'interests'
      get 'subscription'
      get 'subscription_add'
      get 'checkout_form'
      get 'checkout_add'
      post 'gp', action: 'save'
      get 'itinerary'
      get 'finalize'
      put 'publish'
      get 'checkout'
      put 'purchase'
      get 'thankyou'
      post 'toggle_star'
      put 'email_sharer'
    end
    resources 'pitches' do
      member do
        put 'winner'
        put 'remove'
      end
    end
    resource 'plan' do
      member do
        put 'day', action: 'add_day'
        post 'day/:day_id', action: 'update_day'
        delete 'day/:day_id', action: 'delete_day'

        put 'tip_trick', action: 'add_tip_trick'
        post 'tip_trick/:tip_trick_id', action: 'update_tip_trick'
        delete 'tip_trick/:tip_trick_id', action: 'delete_tip_trick'

        put 'booking', action: 'add_booking'
        put 'booking/:booking_id', action: 'add_picture_booking'
        post 'booking/:booking_id', action: 'update_booking'
        delete 'booking/:booking_id', action: 'delete_booking'


        put 'picture', action: 'add_picture'
        delete 'picture/:picture_id', action: 'delete_picture'

        post 'ready', action: 'ready_for_review'
      end
    end
  end

  get     'login'     => 'user_sessions#new'
  delete  'logout'    => 'user_sessions#destroy'
  get     'register'  => 'experts#new'
  get     'home'      => 'home#index'
  get     'hotels'    => 'home#hotels'
  get     'browse'    => 'application#browsexperimental'
  get     'browsexperimental'    => 'application#browsexperimental'
  get     'uikit'    => 'application#uikit'

  namespace :admin do
    get ''  => 'dashboard#index', as: '/'
    get 'expert_list' => 'dashboard#expert_list'
    resources 'itineraries' do
      post 'toggle_published'
    end

    resources 'places' do
      post 'remove_pitch'
    end

    resources 'plans' do
      post 'toggle_published'
      post 'toggle_featured'
    end
  end

  # API ###########################################################
  namespace :api do
    namespace :v1 do
      resources :stories
#      resource :user_sessions, only: :create
      resources :plans, only: [:index]
    end
  end
  #################################################################



  get "/delayed_job" => DelayedJobWeb, anchor: false

  root 'home#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authorize_user
  before_action :authorize_admin

  def index
    if params[:filter] == "experts"
      @users = User.experts.page(params[:page] || 0).per(300)
    elsif params[:filter] == "customers"
      @users = User.customers.page(params[:page] || 0)
    elsif params[:filter] == "admins"
      @users = User.admins.page(params[:page] || 0)
    else
      @users = User.page(params[:page] || 0)
    end
  end

  def expert_list
    @experts = User.experts
    respond_to do |format|
      format.xls
    end
  end
end

app/views/admin/dashboard/expert_list.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Website</Data></Cell>
        <Cell><Data ss:Type="String">Current Location</Data></Cell>
        <Cell><Data ss:Type="String">Hometown</Data></Cell>
        <Cell><Data ss:Type="String">Countries</Data></Cell>
        <Cell><Data ss:Type="String">Cities</Data></Cell>
        <Cell><Data ss:Type="String">Facebook</Data></Cell>
        <Cell><Data ss:Type="String">Instagram</Data></Cell>
        <Cell><Data ss:Type="String">Twitter</Data></Cell>
      </Row>
    <% @experts.each do |expert| %>
      <Row>
        <Cell><Data ss:Type="String"><%= expert.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:website] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:current_location] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:hometown] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:countries] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:cities] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:facebook] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:instagram] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expert.expert_info[:twitter] %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="large-10 large-offset-2 columns">
    <h1>Admin Dashboard</h1>
  </div>
</div>

<div class="row">
  <div class="large-2 columns">
    <%= render 'layouts/parts/admin_menu' %>
  </div>

  <div class="large-10 columns">
    <div class="row">
      <div class="large-9 columns">
        <%= link_to admin_path(filter: "experts"), class: "small secondary button #{ "round" if params[:filter] == 'experts'}" do %>
          <%= image_tag("expert.png") %>Experts
        <% end %>

        <%= link_to admin_path(filter: "customers"), class: "small secondary button #{ "round" if params[:filter] == 'customers'}" do %>
          <%= image_tag("user.png") %>Customers
        <% end %>

        <%= link_to admin_path(filter: "admins"), class: "small secondary button #{ "round" if params[:filter] == 'admins'}" do %>
          <%= image_tag("admin.png") %>Admins
        <% end %>

        <%= link_to admin_path do %>
          <%= image_tag("delete-circle.png", size: "20x20") %>
        <% end %>
      </div>
      <div class="large-3 columns"><%= link_to "Download Expert List", admin_expert_list_path(format: 'xls'), class: "right small button" %></div>
    </div>

    <table style="width:100%">
      <thead>
        <tr>
          <th>Name</th>
          <th>Signed Up</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
        <tr>
          <td><%= image_tag("expert.png") if u.is?("expert") %>
              <%= image_tag("admin.png") if u.is?("admin") %>
              <%= image_tag("user.png") if u.roles_mask.nil? %>
              <%= link_to (u.name || u.email), user_path(u) %></td>
          <td><%= time_ago_in_words u.created_at %></td>
          <td><%= link_to "Delete", user_path(u), method: :delete, data: { confirm: "Please confirm that you want to delete user #{u.name || u.email}." } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>