config/routes.rb
Outtrippin::Application.routes.draw do
  resource 'expert', only: [:create, :show]

  resources 'users', only: [:show, :destroy, :edit, :update] do
    put 'update_avatar'
  end
  resources 'user_sessions', only: [:new, :create, :destroy]
  resources 'password_resets', only: [:new, :create, :edit, :update]

  resources 'itineraries', only: [:index, :show, :create, :update] do
    member do
      get 'details'
      get 'gp'
      get 'email_form'
      get 'duration'
      get 'travelers'
      get 'budget'
      get 'interests'
      get 'subscription'
      get 'subscription_add'
      get 'checkout_form'
      get 'checkout_add'
      post 'gp', action: 'save'
      get 'itinerary'
      get 'finalize'
      put 'publish'
      get 'checkout'
      put 'purchase'
      get 'thankyou'
      post 'toggle_star'
      put 'email_sharer'
    end
    resources 'pitches' do
      member do
        put 'winner'
        put 'remove'
      end
    end
    resource 'plan' do
      member do
        put 'day', action: 'add_day'
        post 'day/:day_id', action: 'update_day'
        delete 'day/:day_id', action: 'delete_day'

        put 'tip_trick', action: 'add_tip_trick'
        post 'tip_trick/:tip_trick_id', action: 'update_tip_trick'
        delete 'tip_trick/:tip_trick_id', action: 'delete_tip_trick'

        put 'booking', action: 'add_booking'
        put 'booking/:booking_id', action: 'add_picture_booking'
        post 'booking/:booking_id', action: 'update_booking'
        delete 'booking/:booking_id', action: 'delete_booking'


        put 'picture', action: 'add_picture'
        delete 'picture/:picture_id', action: 'delete_picture'

        post 'ready', action: 'ready_for_review'
      end
    end
  end

  get     'login'     => 'user_sessions#new'
  delete  'logout'    => 'user_sessions#destroy'
  get     'register'  => 'experts#new'
  get     'home'      => 'home#index'
  get     'hotels'    => 'home#hotels'
  get     'browse'    => 'application#browsexperimental'
  get     'browsexperimental'    => 'application#browsexperimental'
  get     'uikit'    => 'application#uikit'

  namespace :admin do
    get ''  => 'dashboard#index', as: '/'
    get 'expert_list' => 'dashboard#expert_list'
    resources 'itineraries' do
      post 'toggle_published'
    end

    resources 'places' do
      post 'remove_pitch'
    end

    resources 'plans' do
      post 'toggle_published'
      post 'toggle_featured'
    end
  end

  # API ###########################################################
  namespace :api do
    namespace :v1 do
      resources :stories
#      resource :user_sessions, only: :create
      resources :plans, only: [:index]
    end
  end
  #################################################################



  get "/delayed_job" => DelayedJobWeb, anchor: false

  root 'home#index'
end

app/views/layouts/parts/topbar/_right_menu.html.erb
<ul class="right">
  <% if (!@itinerary.nil? && @itinerary.new_record?) || !current_user %>
    <%= content_tag(:li, link_to("Browse Trips", browse_path, id: "browse")) %>
    <%= content_for :body do %>
      <script>
        mixpanel.track_links("#browse", "Clicked Browse Trips", {
          'location': 'Navbar'
        });
      </script>
    <% end %>
  <% end %>
  <% if current_user %>
  <li class="user-menu has-dropdown"><a href="#" ><%= image_tag 'user-menu.png', style: "width:24px;" %><div class="hide-for-medium-up">Me</div></a>
    <ul class="dropdown">
      <%= content_tag(:li, link_to("Admin Dashboard", admin_path)) if current_user.is?("admin") %>
      <%= content_tag(:li, link_to("Dashboard", itineraries_path)) if current_user.has_itineraries? or current_user.is?("expert")  %>
      <%= content_tag(:li, link_to("Profile", user_path(current_user))) if current_user.is?("expert") %>
      <%= content_tag(:li, link_to("Logout", logout_path, method: :delete)) %>
    </ul>
  </li>
  <% else %>
    <%= content_tag(:li, link_to("Login", login_path))  %>
  <% end %>
</ul>