config/routes.rb
Outtrippin::Application.routes.draw do
  resource 'expert', only: [:create, :show]

  resources 'users', only: [:show, :destroy, :edit, :update] do
    put 'update_avatar'
  end
  resources 'user_sessions', only: [:new, :create, :destroy]
  resources 'password_resets', only: [:new, :create, :edit, :update]

  resources 'itineraries', only: [:index, :show, :create, :update] do
    member do
      get 'details'
      get 'gp'
      get 'email_form'
      get 'duration'
      get 'travelers'
      get 'budget'
      get 'interests'
      get 'subscription'
      get 'subscription_add'
      get 'checkout_form'
      get 'checkout_add'
      post 'gp', action: 'save'
      get 'itinerary'
      get 'finalize'
      put 'publish'
      get 'checkout'
      put 'purchase'
      get 'thankyou'
      post 'toggle_star'
      put 'email_sharer'
    end
    resources 'pitches' do
      member do
        put 'winner'
        put 'remove'
      end
    end
    resource 'plan' do
      member do
        put 'day', action: 'add_day'
        post 'day/:day_id', action: 'update_day'
        delete 'day/:day_id', action: 'delete_day'

        put 'tip_trick', action: 'add_tip_trick'
        post 'tip_trick/:tip_trick_id', action: 'update_tip_trick'
        delete 'tip_trick/:tip_trick_id', action: 'delete_tip_trick'

        put 'booking', action: 'add_booking'
        put 'booking/:booking_id', action: 'add_picture_booking'
        post 'booking/:booking_id', action: 'update_booking'
        delete 'booking/:booking_id', action: 'delete_booking'


        put 'picture', action: 'add_picture'
        delete 'picture/:picture_id', action: 'delete_picture'

        post 'ready', action: 'ready_for_review'
      end
    end
  end

  get     'login'     => 'user_sessions#new'
  delete  'logout'    => 'user_sessions#destroy'
  get     'register'  => 'experts#new'
  get     'home'      => 'home#index'
  get     'hotels'    => 'home#hotels'
  get     'browse'    => 'application#browsexperimental'
  get     'browsexperimental'    => 'application#browsexperimental'
  get     'uikit'    => 'application#uikit'

  namespace :admin do
    get ''  => 'dashboard#index', as: '/'
    get 'expert_list' => 'dashboard#expert_list'
    resources 'itineraries' do
      post 'toggle_published'
    end

    resources 'places' do
      post 'remove_pitch'
    end

    resources 'plans' do
      post 'toggle_published'
      post 'toggle_featured'
    end
  end

  # API ###########################################################
  namespace :api do
    namespace :v1 do
      resources :stories
#      resource :user_sessions, only: :create
      resources :plans, only: [:index]
    end
  end
  #################################################################



  get "/delayed_job" => DelayedJobWeb, anchor: false

  root 'home#index'
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  include Chargeable

  acts_as_votable

  belongs_to :user, inverse_of: :itineraries
  has_many :pitches, inverse_of: :itinerary
  has_many :plans, inverse_of: :itinerary

  attr_accessor :source

  default_scope { order('created_at DESC') }

  serialize :extra_info, Hash
  validates_presence_of :destination

  after_create :update_places

  def price
    10 * self.duration.to_i
  end

  def self.published
    Itinerary.where(published: true)
  end

  def price_in_cents(plan)
    if plan == "Single"
      50000
    else
      plan.to_i * self.duration.to_i * 100
    end
  end

  def user_source
    if self.extra_info.has_key?(:source)
      if self.extra_info[:source] == "hotel"
        "Hotel"
      elsif self.extra_info[:source] == "OutTrippin"
        "OutTrippin"
      else
        "Zuji"
      end
    else
      "OutTrippin"
    end
  end
  
  def process_payment(token, plan)
    if self.valid?
      self.charge(token, plan)
      self.paid = true
      self.save
      return true
    else
      return false
    end
  rescue Stripe::CardError => e
    logger.error "Stripe Error"
    errors.add :base, "There was a problem while processing the payment."
    false
  end

  # PITCHES
  def has_winner_pitch?
    !self.pitches.where(winner: true).first.nil?
  end

  def winner_pitch
    self.pitches.where(winner: true).first
  end

  def has_personalized_pitches?
    !self.pitches.where(auto: false).first.nil?
  end

  def has_auto_pitches?
    !self.pitches.where(auto: true).first.nil?
  end

  def get_pitches_from_place(place)
    place.pitches.each do |p|
      copy_pitch = p.dup
      copy_pitch.auto = true
      copy_pitch.winner = false
      copy_pitch.place_id = nil
      copy_pitch.pictures = p.pictures
      copy_pitch.save
      self.pitches << copy_pitch
    end
  end

  # PLANS
  def get_plan_from(user)
    self.plans.where(user: user).first
  end

  def get_plan
    self.plans.first
  end

  def has_plan?
    self.plans.size > 0
  end

  # getters
  def name
    self.extra_info[:name]
  end
  def travelers
    self.extra_info[:travelers]
  end

  def update_places
    sanitized_destination = self.destination.downcase.strip
    place = Place.find_by_name(sanitized_destination)
    if place.nil?
      place = Place.create(name: sanitized_destination)
    else
    end
  end
end

app/controllers/admin/itineraries_controller.rb
class Admin::ItinerariesController < ApplicationController
  before_action :authorize_user
  before_action :authorize_admin

  def index
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
  end

  def toggle_published
    @itinerary = Itinerary.find(params[:itinerary_id])
    @itinerary.published = !@itinerary.published
    @itinerary.save
    redirect_to :back
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    prev_destination = @itinerary.destination.downcase.strip
    new_destination = params[:itinerary][:destination].downcase.strip
    @itinerary.destination = params[:itinerary][:destination]
    @itinerary.departure = params[:itinerary][:departure]
    @itinerary.duration = params[:itinerary][:duration]
    @itinerary.extra_info[:name] = params[:itinerary][:name]
    @itinerary.extra_info[:travelers] = params[:itinerary][:travelers]
    @itinerary.extra_info[:must] = params[:itinerary][:must]
    @itinerary.extra_info[:avoid] = params[:itinerary][:avoid]
    @itinerary.extra_info[:details] = params[:itinerary][:details]
    @itinerary.extra_info[:reward] = params[:itinerary][:reward]
    @itinerary.extra_info[:countdown] = params[:itinerary][:countdown]
    @itinerary.save!
    place = Place.find_by_name(@itinerary.destination.downcase.strip)
    unless place.nil?
      if prev_destination != new_destination
        @itinerary.get_pitches_from_place(place)
      end
    else
      @itinerary.pitches = []
      @itinerary.save
    end

    redirect_to @itinerary
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])
    @itinerary.delete
    redirect_to :back
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_homepage_type, only: [:create]
  before_action :set_itinerary, except: [:index, :create, :browse]
  before_action :load_styles_personalities, only: [:details, :finalize, :update, :publish]
  before_action :authorize_user, only: [:index] # TODO some more actions should be here
  before_action :store_location

  def index
    @itineraries = current_user.itineraries unless current_user.is?("expert")
    @itineraries = Itinerary.published if current_user.is?("expert")
    @starred_itineraries = current_user.find_voted_items
    @pitched_itineraries = Pitch.find_personalized_by_itinerary(current_user)
    @won_itineraries = Pitch.find_winner_expert_by_itinerary(current_user)
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)

    if !itinerary_params[:source].nil?
      @itinerary.extra_info[:source] = itinerary_params[:source]
    end
    
    if @itinerary.save
      if @itinerary.extra_info[:source] == "hotel"
        redirect_to gp_itinerary_path(@itinerary)
      else
        redirect_to details_itinerary_path(@itinerary)
      end
    else
      render 'home/index', layout: 'application'
    end
  end

  def update
    @itinerary_details = ItineraryDetails.new({attributes: params[:itinerary_details], itinerary: @itinerary})
    if @itinerary_details.save
      redirect_to finalize_itinerary_path(@itinerary)
    else
      render 'details'
    end
  end

  def toggle_star
    if current_user.liked? @itinerary
      @itinerary.unliked_by current_user
    else
      current_user.likes @itinerary
    end
    redirect_to :back
  end

  def details
    @itinerary_details = ItineraryDetails.new(itinerary: @itinerary)
  end

  def user
    if @user
      return @user
    else
      @password = generate_password
      @send_user_email = true 
      @user ||= User.new(email: @email, password: @password, password_confirmation: @password)
    end
  end
  
  attr_accessor :email

  def save 
    itinerary = params[:itinerary]
    newuser = params[:user]
    @itinerary.duration = itinerary[:duration]
    @itinerary.departure = itinerary[:departure]
    @itinerary.extra_info[:travelers] = itinerary[:extra_info][:travelers]
    @itinerary.extra_info[:name] = itinerary[:extra_info][:name]
    @itinerary.extra_info[:type] = itinerary[:extra_info][:type]
    @itinerary.extra_info[:time_frame] = itinerary[:extra_info][:time_frame]
    @itinerary.extra_info[:guest_type] = itinerary[:extra_info][:guest_type]
    @itinerary.extra_info[:activity_budget] = itinerary[:extra_info][:activity_budget]
    @itinerary.extra_info[:food_budget] = itinerary[:extra_info][:food_budget]
    @itinerary.extra_info[:age_group] = itinerary[:extra_info][:age_group]
    @itinerary.extra_info[:styles] = itinerary[:extra_info][:styles]
    @itinerary.extra_info[:details] = itinerary[:extra_info][:details]
    @itinerary.extra_info[:subtype] = itinerary[:extra_info][:subtype]
    @itinerary.extra_info[:printType] = itinerary[:extra_info][:printType]
    @itinerary.extra_info[:subscription_id] = itinerary[:extra_info][:subscription_id]
    @email = newuser[:email]
    @user = User.find_by_email(@email)
    user.save!
    if @itinerary.user.nil? 
      @itinerary.user = @user
      @user.roles = ["hotel"]
      user.save
      AdminMailer.delay.new_itinerary_email(@itinerary)
      UserMailer.delay.welcome_user_email(@user, @password, @itinerary) if @send_user_email
    end
    @itinerary.save!

    respond_to do |format|
      format.json { render :json => @export_data.to_json(:include => :user) }
    end
  end

  def gp
     render layout: 'hotelapp'
  end 

  def email_form
    render layout: false
  end 
  
  def travelers
    render layout: false
  end 
  
  def duration
    render layout: false
  end

  def budget
    render layout: false
  end  

  def interests
    render layout: false
  end  

  def subscription
    render layout: false
  end  

  def subscription_add
    render layout: false
  end  

  def checkout_form
    render layout: false
  end  

  def checkout_add
    render layout: false
  end  


  def finalize
    @itinerary_finalize = ItineraryFinalize.new(itinerary: @itinerary)
  end

  def publish
    @itinerary_finalize = ItineraryFinalize.new({attributes: params[:itinerary_finalize], itinerary: @itinerary})
    place = Place.find_by_name(@itinerary.destination.downcase.strip)
    if @itinerary_finalize.save
          # will copy the pitches that exist for this place
          # into the current itinerary (and reset the winners)
      @itinerary.get_pitches_from_place(place)
      if !current_user
        flash[:notice] = "Looks like there's already an account with that email address. Please login to continue! :)"
        session[:original_uri] = checkout_itinerary_path(@itinerary)
        redirect_to login_path
      else
        # check if we already have piches to add!
        if place.nil?
          redirect_to checkout_itinerary_path(@itinerary)
        else
          redirect_to itinerary_path(@itinerary)
        end
      end
    else
      render 'finalize'
    end
  end

  def show
    @plan = @itinerary.plans.first if @itinerary.has_plan?
    if current_user
      @pitches = @itinerary.pitches
      @pitch = @pitches.where(user: current_user).first if current_user.is?("expert")
    end
    # TODO SET SOME PERMISSION HERE
    # authorize_user is not enough
  end

  def checkout
    @featuring_stories = FeaturedPlan.all.map { |p| p.plan }

    if !current_user
      flash[:notice] = "You have to login before getting to the checkout page."
      session[:original_uri] = checkout_itinerary_path(@itinerary)
      redirect_to login_path
    end
  end

  def browse
    @featuring_stories = Plan.where(published: true)
    @itinerary = Itinerary.new
  end

  def purchase
    token = params[:stripeToken]
    plan = params[:plan]

    if @itinerary.process_payment(token, plan)
      UserMailer.delay.payment_received_email(@itinerary.user, @itinerary)
      AdminMailer.delay.payment_received_email(@itinerary)
      flash[:fresh_purchase] = true
      if @itinerary.extra_info[:source] == "hotel"
        redirect_to itineraries_path
      else
        redirect_to thankyou_itinerary_path(@itinerary)
      end
    else
      if @itinerary.extra_info[:source] == "hotel"
        render 'gp'
      else
        render 'checkout'
      end
    end
  end

  def thankyou
    if flash[:fresh_purchase]
    elsif false # TODO: if itinerary is not paid, take it to the checkout page
    else
      redirect_to root_url
    end
  end

  def email_sharer
    @destination = params[:emails].split(',')
    UserMailer.delay.email_sharer_email(@destination, params[:message], @itinerary)
    flash[:notice] = "Emails are on their way!"
    redirect_to :back
  end

  private

  def generate_password
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    (0...8).map{ o[rand(o.length)] }.join
  end

  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end

  def itinerary_params
    params.require(:itinerary).permit(:destination, :source)
  end

  # TODO REFACTOR THIS
  def load_styles_personalities
    @styles = YAML.load_file(File.join(Rails.root.to_s, 'config', 'styles.yml'))
    @personalities = YAML.load_file(File.join(Rails.root.to_s, 'config', 'personalities.yml'))
    @booked = YAML.load_file(File.join(Rails.root.to_s, 'config', 'booked.yml'))
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
  def get_date_options(quantity)
    options = ["Haven't decided"]
    now = Time.now
    time = Time.utc(now.year, now.month, 1, 0, 0, 0)

    quantity.times do
      options << time.strftime("%B") + ", " + time.year.to_s
      time = time .advance(months: 1)
    end

    return options
  end

  def activity_budget_options
    ['$0-50', '$50-100', '$100-200', '$200+']
  end

  def accommodation_budget_options
    ['$0-50', '$50-100', '$100-200', '$200-500', '$500+']
  end

  def expanded_sidebar
    content_for :body do
      "<script>window.showSidebar();</script>".html_safe
    end
  end

    def full_pitch
    content_for :body do
      "<script>window.showPitch();</script>".html_safe
    end
  end

  # helpers for step bar  ##########################
  def steps
    %w(describe launch pick)
  end

  def left_bar_or_space(index, steps)
    return "&nbsp;" if (index == 1)
    "<hr />"
  end

  def right_bar_or_space(index, steps)
    return "&nbsp;" if (index == steps.length)
    "<hr />"
  end
  ##################################################

 # helpers for step bar  ##########################
  def expert_steps
    ['Submit a pitch', 'The requestor picks a winner', 'Winner writes the story']
  end

  def left_bar_or_space(index, steps)
    return "&nbsp;" if (index == 1)
    "<hr />"
  end

  def right_bar_or_space(index, steps)
    return "&nbsp;" if (index == steps.length)
    "<hr />"
  end
  ##################################################

  def expert_info_website_url(website)
    "http://" + website
  end

  def expert_info_twitter_url(handle)
    "http://twitter.com/" + handle
  end

  def expert_info_google_url(handle)
    "http://" + handle + "?rel=author"
  end
  
  def expert_info_instagram_url(handle)
    "http://instagram.com/" + handle
  end

  def pitches_so_far(itinerary)
    return "No pitches in so far" if itinerary.pitches.nil?
    itinerary.pitches.count == 1 ? "1 pitch in so far." : "#{itinerary.pitches.count} pitches in so far."
  end

end

app/views/itineraries/show/_admin.html.erb
<% if @plan && @plan.published %>
  <%= render @plan %>
<% elsif @itinerary.has_winner_pitch? %>
<% set_page_title(@itinerary.winner_pitch.title.blank? ? "Trip to " + @itinerary.destination + " - OutTrippin" : @itinerary.winner_pitch.title + " - OutTrippin") %>
<% set_page_desc( @itinerary.winner_pitch.summary ) %>
<style>
.cover { background-image: none; height:300px; }
#overlay {height:300px;}
.header {top:80px; overflow: visible;}
.tabs {top:240px;}
</style>
<div class="row">
  <div class="small-12 small-centered columns">
     <%= render 'expertsteps', expert_step: 'Winner writes the story', disable: %w() %>
    <div class="large-8 large-centered small-12 columns">
      <h2 style="margin-top:20px;" class="white">Winner has been chosen. <a href="#" data-dropdown="submitpitchd" data-options="is_hover:true"><%= image_tag 'question-w.png', style: "width:15px; margin-top:-30px;" %></a></h2>  
    </div>
    <div id="submitpitchd" class="f-dropdown medium content" data-dropdown-content>
      <h5>The traveler has picked their favorite expert.</h5>
      <p style="font-size:0.850em;"><strong>How it works:</strong>
      The traveler has chosen their favorite expert and they are now working on building their personalized travel story. The winning pitch is featured below.</p>
      <hr>
      <p>If you're ever have any issues or questions for us at OutTrippin, just hit the <%= image_tag 'question-box.png', style: "height:1.5em; margin-top:-.5em;" %> on the bottom right and we'll get back to you in a flash.</p>
    </div>

  </div>
</div>
</div class="header">
<div class="tabs">
  <div class="row">
    <div class="large-12 large-centered text-center small-12 columns">
      <div class="large-8 large-centered text-center small-12 columns">
        <ul id="cover-tabs" class="inline-list cover-tabs text-center no-margin sans">
          <li><a href="#" id="slide0" class="active-tab">WINNING PITCH</a></li>
          <li><%= link_to "EDIT STORY", itinerary_plan_path(@itinerary)%></li>
          <li><a href="#" id="slide2" >TRAVELER'S REQUEST</a></li>
          <li><a href="#" id="slide1">ALL PITCHES</a></li>
        </ul>
        <hr style="border-color:white; margin-top:0;">
      </div>
    </div>
  </div>
</div>
<div class="row" id="slide0-content">
  <div class="large-12 large-centered small-12 columns">
    <%= render @itinerary.winner_pitch %>
  </div>
</div>
<div id="slide1-content"> 
	<%= render @pitches %>
</div>
<div class="row" id="slide2-content">
  <div class="large-12 large-centered small-12 columns">
      <%= render 'itineraries/itinerary_full' %>
  </div>
  <div class="written-by">
    <div class="large-12 large-centered small-12 columns">
      <div class="large-8 large-centered small-12 columns">
        <%= render 'itineraries/show/comments' %>
      </div>
    </div>
  </div>
</div>

<% elsif @pitches.blank? %>
<style>
.cover { background-image: none; height:300px; }
#overlay {height:300px;}
.header {top:80px; overflow: visible;}
.tabs {top:240px;}
</style>
<div class="row">
  <div class="small-12 small-centered columns">
     <%= render 'expertsteps', expert_step: 'Submit a pitch', disable: %w() %>
    <div class="large-8 large-centered small-12 columns">
      <h2 style="margin-top:20px;" class="white">Accepting pitches now. <a href="#" data-dropdown="submitpitchd" data-options="is_hover:true"><%= image_tag 'question-w.png', style: "width:15px; margin-top:-30px;" %></a></h2>  
    </div>
    <div id="submitpitchd" class="f-dropdown medium content" data-dropdown-content>
      <h5>No pitches have been submited yet.</h5>
      <p style="font-size:0.850em;"><strong>How it works:</strong>
      First step is to put in a fantastic pitch. If the requestor picks you as their favorite, you'll have the opportunity to write the full story. Cool?  Hit the <%= image_tag 'submit-a-pitch.png', style: "height:1.5em; margin-top: -0.5em;" %> button below to get started!</p>
      <hr>
      <p>If you're ever have any issues or questions for us at OutTrippin, just hit the <%= image_tag 'question-box.png', style: "height:1.5em; margin-top:-.5em;" %> on the bottom right and we'll get back to you in a flash.</p>
    </div>

  </div>
</div>
</div class="header">
<div class="tabs">
  <div class="row">
    <div class="large-12 large-centered text-center small-12 columns">
      <div class="large-8 large-centered text-center small-12 columns">
        <ul id="cover-tabs" class="inline-list cover-tabs text-center no-margin sans">
          <li><a href="#" id="slide0" class="active-tab" >TRAVELER'S REQUEST</a></li>
        </ul>
        <hr style="border-color:white; margin-top:0;">
      </div>
    </div>
  </div>
</div>

<div class="row" id="slide0-content">
  <div class="large-12 large-centered small-12 columns">
      <%= render 'itineraries/itinerary_full' %>
  </div>
  <div class="written-by">
    <div class="large-12 large-centered small-12 columns">
      <div class="large-8 large-centered small-12 columns">
        <%= render 'itineraries/show/comments' %>
      </div>
    </div>
  </div>
</div><div class="share break">
  <h4 class="serif subheader"><em><%= link_to "Submit a pitch", new_itinerary_pitch_path(@itinerary), target:"blank", class: "sharethis" %></em></h4>
  <hr style="border: 1px #cccccc solid;margin-top: -30px;z-index: 9;">
</div>

<% else %>
<style>
.cover { background-image: none; height:300px; }
#overlay {height:300px;}
.header {top:80px; overflow: visible;}
.tabs {top:240px;}
</style>
<div class="row">
  <div class="small-12 small-centered columns">
     <%= render 'expertsteps', expert_step: 'The requestor picks a winner', disable: %w() %>
    <div class="large-8 large-centered small-12 columns">
      <h2 style="margin-top:20px;" class="white">Still accepting pitches. <a href="#" data-dropdown="submitpitchd" data-options="is_hover:true"><%= image_tag 'question-w.png', style: "width:15px; margin-top:-30px;" %></a></h2>  
    </div>
    <div id="submitpitchd" class="f-dropdown medium content" data-dropdown-content>
      <h5>The story request is still accepting pitches.</h5>
      <p style="font-size:0.850em;"><strong>How it works:</strong>
      The traveler has received expert pitches but has not yet picked a winner.</p>
      <hr>
      <p>If you're ever have any issues or questions for us at OutTrippin, just hit the <%= image_tag 'question-box.png', style: "height:1.5em; margin-top:-.5em;" %> on the bottom right and we'll get back to you in a flash.</p>
    </div>

  </div>
</div>
</div class="header">
<div class="tabs">
  <div class="row">
    <div class="large-12 large-centered text-center small-12 columns">
      <div class="large-8 large-centered text-center small-12 columns">
        <ul id="cover-tabs" class="inline-list cover-tabs text-center no-margin sans">
          <li><a href="#" id="slide0" class="active-tab">TRAVELER'S REQUEST</a></li>
          <li><a href="#" id="slide1">ALL PITCHES</a></li>
        </ul>
        <hr style="border-color:white; margin-top:0;">
      </div>
    </div>
  </div>
</div>

<div id="slide1-content"> 
  <%= render @pitches %>	
</div>
<div class="row" id="slide0-content">
  <div class="large-12 large-centered small-12 columns">
      <%= render 'itineraries/itinerary_full' %>
  </div>
  <div class="written-by">
    <div class="large-12 large-centered small-12 columns">
      <div class="large-8 large-centered small-12 columns">
        <%= render 'itineraries/show/comments' %>
      </div>
    </div>
  </div>
</div>
<div class="share break">
  <h4 class="serif subheader"><em><%= link_to "Submit a pitch", new_itinerary_pitch_path(@itinerary), target:"blank", class: "sharethis" %></em></h4>
  <hr style="border: 1px #cccccc solid;margin-top: -30px;z-index: 9;">
</div>

<% end %>

app/views/itineraries/show/_comments.html.erb
<p class="sans subheader"><small>PUBLIC COMMENTS & DISCUSSION<a href="#" data-dropdown="commentsd" data-options="is_hover:true"><%= image_tag 'question.png', style: "width:10px; margin:-4px 0 0 5px; opacity:0.7;" %></a></small></p>
<div id="commentsd" class="f-dropdown medium content" data-dropdown-content>
    <p>To be notified when new comments are made, please click the <strong>"Subscribe"</strong> button at the bottom of the comments section. During the beta stage, automatic notifications are not turned on.</p>
</div>

<div id="disqus_thread" class="short-break"></div>
<script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'outtrippin'; // required: replace example with your forum shortname
        var disqus_url = '<%= "http://outtrippin.com/itineraries/" +  @itinerary[:id].to_s %>';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

<div id="disqus_thread"></div>

<%= content_for :body do %>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'outtrippin'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>
<% end %>